config/routes.rb
Rails.application.routes.draw do

  # Home / Root
  root 'welcome#index'
  get 'welcome/index'

  # Individual pages Routes
  get '/companies/:company_id/users/:id/index' => "audio#index", as:'audio_index'
  get "/companies/:id/dashboard/show" => "dashboard#show", as: "dashboard"
  get '/users/:id/video' => "video#show", as: 'user_video'
  get '/companies/:company_id/users/:id/text_analysis' => 'text#show', as: 'text_analyze'

 post 'users/:id/texts'=>'text#create', as:"text_upload"
  # Braintree Payment Routes
  get 'braintree/new'
  get 'braintree/new_six'
  get 'braintree/new_one'
  get 'braintree/pricing'
  post 'braintree/checkout'
  post 'braintree/checkout_six'
  post 'braintree/checkout_one'
  post 'braintree/checkout_one_existing'

  # Clearance Routes
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get '/show'=>"video#show"  ,as: "video_feature"

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :users, controller:'users'
  resources :companies, controller:'company'

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :companies do
    resource :request, controller: 'request'
  end

  # Google Oauth Callback Route
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  post 'braintree/checkout'
  post 'braintree/checkout_six'
  post 'braintree/checkout_one'
  get 'companies/:company_id/users/:id/confirm' => 'users#confirm', as:'confirm_user'
  get 'companies/:id/employees_index' => 'company#employees_index', as:'employees_index'
  patch 'users/:id/remove_employee' => 'company#remove_employee', as:'remove_employee'
  get '/subscribe_to_plan' => 'braintree#subscribe_to_plan', as:'subscribe_to_plan'
  get '/pricing' => 'braintree#pricing', as:'pricing'

  post '/companies/:id/search_employees' => 'company#search', as: 'search_company_employees'
  post '/companies/search' => 'company#search_all_companies', as: 'search_companies'

end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
  def new
    @client_token = Braintree::ClientToken.generate
  end

  def new_six
    @client_token = Braintree::ClientToken.generate
  end

  def new_one
    @client_token = Braintree::ClientToken.generate
  end

  def pricing
    render 'pricing'
  end

  def checkout_one
    nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

    customer = current_user.find_or_create_braintree_customer(nonce_from_the_client)

    result = Braintree::Subscription.create(
      :plan_id => 'hr8m',
      :payment_method_token => customer.payment_methods[0].token
      )

    if result.success?
      redirect_to :root, :flash => { :success => "Transaction successful!" }
    else
      redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
    end
  end

  def checkout_six
    nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

    customer = current_user.find_or_create_braintree_customer(nonce_from_the_client)

    result = Braintree::Subscription.create(
      :plan_id => '9s3g',
      :payment_method_token => customer.payment_methods[0].token
      )

    if result.success?
      redirect_to :root, :flash => { :success => "Transaction successful!" }
    else
      redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
    end
  end

  def checkout
    nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

    customer = current_user.find_or_create_braintree_customer(nonce_from_the_client)

    result = Braintree::Subscription.create(
      :plan_id => 'qqfr',
      :payment_method_token => customer.payment_methods[0].token
      )

    if result.success?
      redirect_to :root, :flash => { :success => "Transaction successful!" }
    else
      redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
    end
  end

end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/views/braintree/new.html.erb
<div class='container'>
  <h1>12 Month Subscription</h1>
  <div class="card">
    <div class="card-header">
    </div>
    <div class="card-body">
      <div class="container">
        <div class="row">
          <div class="col-sm">
            <h5>You're almost ready, just place a payment to join Empath.</h5>
            <%= form_for :checkout_form, url: braintree_checkout_path, html: { id: "cardForm"} do |form| %>

              <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
              <div id="card-number" class="hosted-field"></div>

              <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
              <div id="expiration-date" class="hosted-field"></div>

              <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
              <div id="cvv" class="hosted-field"></div>

              <%= form.hidden_field "payment_method_nonce" %>

              <div class="button-container">
                <%= form.submit "Purchase", disabled: true, class: "btn btn-success", id: "submit-payment-btn", style:'width:100%' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
var form = document.querySelector('#cardForm');
var submit = document.querySelector("#submit-payment-btn");
var authorization = '<%= @client_token %>';

braintree.client.create({
  // Replace this with your own authorization.
  authorization: authorization
}, function (clientErr, clientInstance) {
  if (clientErr) {
    // Handle error in client creation
    return;
  }

  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '14pt'
      },
      'input.invalid': {
        'color': 'red'
      },
      'input.valid': {
        'color': 'green'
      }
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '4111 1111 1111 1111'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '123'
      },
      expirationDate: {
        selector: '#expiration-date',
        placeholder: '10/2019'
      }
    }
  }, function (hostedFieldsErr, hostedFieldsInstance) {
    if (hostedFieldsErr) {
      // Handle error in Hosted Fields creation
      return;
    }

    submit.removeAttribute('disabled');

    form.addEventListener('submit', function (event) {
      event.preventDefault();

      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
        if (tokenizeErr) {
          // Handle error in Hosted Fields tokenization
          return;
        }

        // Put `payload.nonce` into the `payment_method_nonce` input, and then
        // submit the form. Alternatively, you could send the nonce to your server
        // with AJAX.
        document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
        form.submit();
      });
    }, false);
  });
});
</script>

app/views/braintree/new_one.html.erb
<div class='container'>
  <h1>1 Month Subscription</h1>
  <div class="card">
    <div class="card-header">
    </div>
    <div class="card-body">
      <div class="container">
        <div class="row">
          <div class="col-sm">
            <h5>You're almost ready, just place a payment to join Empath.</h5>
            <%= form_for :checkout_form, url: braintree_checkout_one_path, html: { id: "cardForm"} do |form| %>

              <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
              <div id="card-number" class="hosted-field"></div>

              <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
              <div id="expiration-date" class="hosted-field"></div>

              <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
              <div id="cvv" class="hosted-field"></div>

              <%= form.hidden_field "payment_method_nonce" %>

              <div class="button-container">
                <%= form.submit "Purchase", disabled: true, class: "btn btn-success", id: "submit-payment-btn", style:'width:100%' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



<script>
var form = document.querySelector('#cardForm');
var submit = document.querySelector("#submit-payment-btn");
var authorization = '<%= @client_token %>';

braintree.client.create({
  // Replace this with your own authorization.
  authorization: authorization
}, function (clientErr, clientInstance) {
  if (clientErr) {
    // Handle error in client creation
    return;
  }

  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '14pt'
      },
      'input.invalid': {
        'color': 'red'
      },
      'input.valid': {
        'color': 'green'
      }
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '4111 1111 1111 1111'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '123'
      },
      expirationDate: {
        selector: '#expiration-date',
        placeholder: '10/2019'
      }
    }
  }, function (hostedFieldsErr, hostedFieldsInstance) {
    if (hostedFieldsErr) {
      // Handle error in Hosted Fields creation
      return;
    }

    submit.removeAttribute('disabled');

    form.addEventListener('submit', function (event) {
      event.preventDefault();

      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
        if (tokenizeErr) {
          // Handle error in Hosted Fields tokenization
          return;
        }

        // Put `payload.nonce` into the `payment_method_nonce` input, and then
        // submit the form. Alternatively, you could send the nonce to your server
        // with AJAX.
        document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
        form.submit();
      });
    }, false);
  });
});
</script>

app/views/braintree/new_six.html.erb
<div class='container'>
  <h1>6 Month Subscription</h1>
  <div class="card">
    <div class="card-header">
    </div>
    <div class="card-body">
      <div class="container">
        <div class="row">
          <div class="col-sm">
            <h5>You're almost ready, just place a payment to join Empath.</h5>
            <%= form_for :checkout_form, url: braintree_checkout_six_path, html: { id: "cardForm"} do |form| %>

              <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
              <div id="card-number" class="hosted-field"></div>

              <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
              <div id="expiration-date" class="hosted-field"></div>

              <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
              <div id="cvv" class="hosted-field"></div>

              <%= form.hidden_field "payment_method_nonce" %>

              <div class="button-container">
                <%= form.submit "Purchase", disabled: true, class: "btn btn-success", id: "submit-payment-btn", style:'width:100%' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
var form = document.querySelector('#cardForm');
var submit = document.querySelector("#submit-payment-btn");
var authorization = '<%= @client_token %>';

braintree.client.create({
  // Replace this with your own authorization.
  authorization: authorization
}, function (clientErr, clientInstance) {
  if (clientErr) {
    // Handle error in client creation
    return;
  }

  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '14pt'
      },
      'input.invalid': {
        'color': 'red'
      },
      'input.valid': {
        'color': 'green'
      }
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '4111 1111 1111 1111'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '123'
      },
      expirationDate: {
        selector: '#expiration-date',
        placeholder: '10/2019'
      }
    }
  }, function (hostedFieldsErr, hostedFieldsInstance) {
    if (hostedFieldsErr) {
      // Handle error in Hosted Fields creation
      return;
    }

    submit.removeAttribute('disabled');

    form.addEventListener('submit', function (event) {
      event.preventDefault();

      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
        if (tokenizeErr) {
          // Handle error in Hosted Fields tokenization
          return;
        }

        // Put `payload.nonce` into the `payment_method_nonce` input, and then
        // submit the form. Alternatively, you could send the nonce to your server
        // with AJAX.
        document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
        form.submit();
      });
    }, false);
  });
});
</script>

app/views/braintree/pricing.html.erb
<div class="container-fluid bg-dark" style="height: 100vh;">
  <h1 class="text-center text-white pt-5" style="font-weight: 700;">Start engaging with your customers better.</h1>
  <h4 class="text-center text-white mb-5" style="font-weight: 300;">Try it for free for the first 7-days.</h4>

  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-auto">
        <div class="card-deck">
          <div class="card text-center mt-3" style="width: 25rem;">
            <div class="card-header bg-success">
              <strong>Basic Plan</strong>
            </div>
            <div class="card-body">
              <h1><i class="fas fa-user-friends text-muted"></i></h1>
              <h2 class="card-title mt-5">$5.99 / month</h2>
              <p class="card-text">
                10 Employees </br></br>
                20 MB of storage </br>
                You may fax us. </br>
                Help Center access</p>
                <%=link_to 'Start 7-day Free Trial', braintree_new_one_path, class:'btn btn-outline-success mt-5'%>
              </div>
              <div class="card-footer">
                <strong>Best for:</strong> People that are broke
              </div>
            </div>

            <div class="card text-center mt-3">
              <div class="card-header bg-primary">
                <strong>Standard Plan</strong>
              </div>
              <div class="card-body">
                <h1><i class="fas fa-building text-muted"></i></h1>
                <h2 class="card-title mt-5">$8.99 / month</h2>
                <p class="card-text">
                  10-100 Employees (SME) </br></br>
                  100 GB of Storage </br>
                  Email and Phone Support </br>
                  Help Center access</p>
                  <%=link_to 'Subscribe to this Plan', braintree_new_six_path, class:'btn btn-outline-success mt-5'%>
                </div>
                <div class="card-footer">
                  <strong>Best for:</strong> Small Businesses
                </div>
              </div>

              <div class="card text-center mt-3">
                <div class="card-header bg-warning">
                  <strong>Enterprise Plan</strong>
                </div>
                <div class="card-body">
                  <h1><i class="fas fa-city text-muted"></i></h1>
                  <h2 class="card-title mt-5">$14.99 / month</h2>
                  <p class="card-text">
                    1000+ Employees </br></br>
                    Unlimited Storage </br>
                    On-site Support </br>
                    <strong>Everything, basically.</strong> </br>
                    <%=link_to 'Subscribe to this Plan', braintree_new_path, class:'btn btn-outline-success mt-5'%>
                  </div>
                  <div class="card-footer">
                    <strong>Best for:</strong> High-Rollers
                  </div>
                </div>
              </div>
      </div>
    </div>
  </div>
</div>

app/views/braintree/subscribe_to_plan.html.erb
<h1>Pick a Plan</h1>

<div class="card mb-4" style="width: 20rem; height: 25rem; text-align:left">
<img class="card-img-top" src='#'%> alt="Card image cap">
<div class="card-body">
    <h3 class="card-title"><%= link_to "1 month plan", braintree_new_one_path %></h3>
</div>
</div>

<div class="card mb-4" style="width: 20rem; height: 25rem; text-align:left">
<img class="card-img-top" src='#'%> alt="Card image cap">
<div class="card-body">
    <h3 class="card-title"><%= link_to "6 month plan", braintree_new_six_path %></h3>
</div>
</div>

<div class="card mb-4" style="width: 20rem; height: 25rem; text-align:left">
<img class="card-img-top" src='#'%> alt="Card image cap">
<div class="card-body">
    <h3 class="card-title"><%= link_to "12 month plan", braintree_new_path %><br></h3>
</div>
</div>