config/routes.rb
Rails.application.routes.draw do

  # Home / Root
  root 'welcome#index'
  get 'welcome/index'

  # Individual pages Routes
  get '/companies/:company_id/users/:id/index' => "audio#index", as:'audio_index'
  get "/companies/:id/dashboard/show" => "dashboard#show", as: "dashboard"
  get '/users/:id/video' => "video#show", as: 'user_video'
  get '/companies/:company_id/users/:id/text_analysis' => 'text#show', as: 'text_analyze'

 post 'users/:id/texts'=>'text#create', as:"text_upload"
  # Braintree Payment Routes
  get 'braintree/new'
  get 'braintree/new_six'
  get 'braintree/new_one'
  get 'braintree/pricing'
  post 'braintree/checkout'
  post 'braintree/checkout_six'
  post 'braintree/checkout_one'
  post 'braintree/checkout_one_existing'

  # Clearance Routes
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get '/show'=>"video#show"  ,as: "video_feature"

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :users, controller:'users'
  resources :companies, controller:'company'

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :companies do
    resource :request, controller: 'request'
  end

  # Google Oauth Callback Route
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  post 'braintree/checkout'
  post 'braintree/checkout_six'
  post 'braintree/checkout_one'
  get 'companies/:company_id/users/:id/confirm' => 'users#confirm', as:'confirm_user'
  get 'companies/:id/employees_index' => 'company#employees_index', as:'employees_index'
  patch 'users/:id/remove_employee' => 'company#remove_employee', as:'remove_employee'
  get '/subscribe_to_plan' => 'braintree#subscribe_to_plan', as:'subscribe_to_plan'
  get '/pricing' => 'braintree#pricing', as:'pricing'

  post '/companies/:id/search_employees' => 'company#search', as: 'search_company_employees'
  post '/companies/search' => 'company#search_all_companies', as: 'search_companies'

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :authentications, dependent: :destroy
  has_many :notifications, foreign_key: :recipient_id, dependent: :destroy
  
  mount_uploader :image, ImageUploader
  belongs_to :company, optional: true
  has_many :databases, dependent:  :destroy
  has_many :videos, dependent:  :destroy
  enum position: { manager: 'Manager', employee: 'Employee'}
 
  def self.create_with_auth_and_hash(authentication, auth_hash)
    user = self.create!(
      firstname: auth_hash["info"]["name"],
      email: auth_hash["info"]["email"],
      password: SecureRandom.hex(10)
    )
    user.authentications << authentication
    return user
  end
 
  # grab google to access google for user data
  def google_token
    x = self.authentications.find_by(provider: 'google_oauth2')
    return x.token unless x.nil?
  end

  def find_or_create_braintree_customer(nonce_from_the_client)
    if self.braintree_customer_id 
      Braintree::Customer.find(self.braintree_customer_id)
      # byebug
    else
      result = Braintree::Customer.create(
      first_name: self.firstname,
      last_name: self.lastname,
      payment_method_nonce: nonce_from_the_client
      )
      self.update(braintree_customer_id: result.customer.id)
      result.customer
    end
  end

  def get_existing_braintree_customer
    Braintree::Customer.find(self.braintree_customer_id)
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
    def show
        @user = User.find(params[:id])
    end
    def update
        @user = User.find(params[:id])
        @user.update(user_params)
        redirect_to @user
    end

    def create
        # byebug
        @user = User.new(user_params)
        @user.save
        sign_in(@user)
        redirect_to pricing_path
    end

    def confirm
        @user = User.find(params[:id])
        @user.update(company_id:params[:company_id])
        redirect_back(fallback_location: root_path)
    end
    
    def subscribe_to_plan
    end
    
    private 

    # Override user_from_params from default clearance controller
    def user_from_params
        email = user_params.delete(:email)
        password = user_params.delete(:password)
        firstname = user_params.delete(:firstname)
        lastname = user_params.delete(:lastname)
        position = user_params.delete(:position)
    
        Clearance.configuration.user_model.new(user_params).tap do |user|
          user.email = email
          user.password = password
          user.firstname = firstname
          user.lastname = lastname
          user.position = position
        end
    end
    
    def user_params
        params.require(:user).permit(:email, :password, :firstname, :lastname, :position, :image)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email'%>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

<div class="text-field">
  <%= form.label :'First name' %>
  <%= form.text_field :firstname %>
</div>

<div class="text-field">
  <%= form.label :'Last name' %>
  <%= form.text_field :lastname %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.firstname %></h1>
<div class="card" style="width: 20rem;">
            <img class="card-img-top" src=<%= @user.image_url(:thumb).to_s %> alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title"><%= @user.firstname.upcase %> | <%=@user.age %></h5>
                <h6> Email <%=@user.email %> </h6>
                <% if @user.id == current_user.id %>
                <p>
                    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                        Update 
                    </button>
                </p>
                <div class="collapse" id="collapseExample">
                    <div class="card card-body">
                            <%= form_for @user, :html => {:multipart => true}, local: true do |form| %>
                                <p>
                                    <%= form.label :"Update name" %><br>
                                    <%= form.text_field :firstname %>
                                </p>
                                <p>
                                    <%= form.file_field :image %>
                                    <%= form.button :submit => "", class: "btn btn-primary btn-xs" %>
                                </p>
                            <% end %>
                    </div>
                </div>
                <% end %>
            </div>
        </div>