config/routes.rb
Rails.application.routes.draw do

  # Home / Root
  root 'welcome#index'
  get 'welcome/index'

  # Individual pages Routes
  get '/companies/:company_id/users/:id/index' => "audio#index", as:'audio_index'
  get "/companies/:id/dashboard/show" => "dashboard#show", as: "dashboard"
  get '/users/:id/video' => "video#show", as: 'user_video'
  get '/companies/:company_id/users/:id/text_analysis' => 'text#show', as: 'text_analyze'

 post 'users/:id/texts'=>'text#create', as:"text_upload"
  # Braintree Payment Routes
  get 'braintree/new'
  get 'braintree/new_six'
  get 'braintree/new_one'
  get 'braintree/pricing'
  post 'braintree/checkout'
  post 'braintree/checkout_six'
  post 'braintree/checkout_one'
  post 'braintree/checkout_one_existing'

  # Clearance Routes
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get '/show'=>"video#show"  ,as: "video_feature"

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :users, controller:'users'
  resources :companies, controller:'company'

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :companies do
    resource :request, controller: 'request'
  end

  # Google Oauth Callback Route
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  post 'braintree/checkout'
  post 'braintree/checkout_six'
  post 'braintree/checkout_one'
  get 'companies/:company_id/users/:id/confirm' => 'users#confirm', as:'confirm_user'
  get 'companies/:id/employees_index' => 'company#employees_index', as:'employees_index'
  patch 'users/:id/remove_employee' => 'company#remove_employee', as:'remove_employee'
  get '/subscribe_to_plan' => 'braintree#subscribe_to_plan', as:'subscribe_to_plan'
  get '/pricing' => 'braintree#pricing', as:'pricing'

  post '/companies/:id/search_employees' => 'company#search', as: 'search_company_employees'
  post '/companies/search' => 'company#search_all_companies', as: 'search_companies'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<!-- Landing Page -->
<nav class="customnav navbar navbar-expand-lg navbar-dark sticky-top bg-white border-bottom border-muted">
  <a class="navbar-brand text-dark" href="/"><i class="fas fa-brain mr-1"></i>Empath</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarSupportedContent">

    <%= form_with url: search_companies_path, local: true, class:'form-inline my-2 my-lg-0' , :method => 'post', id: "search-companies"  do |form| %>
      <%= form.text_field :searchcompany, class: "form-control mr-sm-2", list: 'list', id:"main-search", placeholder:"Search for a Company" %>
      <%= form.submit "Search", class:"btn btn-outline-primary my-2 my-sm-0" %>
      <datalist id="list"></datalist>
    <% end %>

    <div class="navbar-links">
      <ul class="navbar-nav mr-auto">
        <!-- <li class="nav-item"> -->
          <%#= link_to "Profile", user_path(current_user.id), class: "nav-link mr-3" %>
        <!-- </li> -->
        <% if signed_in? -%>
        <li class="nav-item">
        <!-- <li class="nav-item">
          <%#= link_to "Facial Expression", video_path, class: "nav-link  mr-3" %>
        </li>
        <li class="nav-item">
          <%#= link_to "Speech", index_path, class: "nav-link mr-3" %>
        </li>
        <li class="nav-item">
          <%#= link_to "Text", index_path, class: "nav-link mr-3" %>
        </li> -->
        <li class="nav-item">
          <%= link_to "Pricing", braintree_pricing_path, class: "nav-link mr-3" %>
        </li>
        <% if current_user.company_id == nil %>
          <li class='nav-item'>
          <%= link_to "Create Company", new_company_path, class: "nav-link mr-3" %>
          </li>
        <% end %>
        <% if current_user.company_id != nil %>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path(current_user.company.id), class: "nav-link mr-3" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to t(".sign_out"), sign_out_path, method: :delete, class:"nav-link" %>
          <% end -%>
        </li>
      </ul>
    </div>

  </div>
</nav>

<div class="container-fluid">
  <div class="container-fluid">
    <div class="row">
      <div id = "hero-showcase-left" class="container-fluid d-flex">
        <div class="col-6 d-inline-block mr-2 pl-0 mt-3">
          <%= image_tag "welcome.jpg", class:"card-img-top border border-muted" %>
        </div>

        <div id="hero-showcase-right" class="col-md-6 d-inline-block mt-3 bg-white shadow-lg rounded border border-muted">
          <h1 class="pl-5 pr-5 pt-5 mt-5" style="font-size: 42px;"><strong>Empathise</strong> with your customers <strong>effectively.</strong></h1>
          <p class="hero pl-5 pr-5 pt-4"> Use our emotional analysis tools to gain valuable insights on your customers facial expressions, speech, and text sentiments.</p>
          <p class="hero pl-5 pr-5 pb-3"> Drastically improve the way your business handles the customer experience - <strong>Get started today.</strong></p>
          <% if signed_out? %>
            <div class="container pl-5 text-center">
              <%= form_for :user, url: users_path, local:true, :method => 'post' do |form| %>
                <!--<input id="password-field" class= "form-control mb-2" type="text" name="First Name" placeholder="First Name" style="width: 565px;">-->
                <%= form.text_field :firstname, class:'form-control mb-2', placeholder:'First Name'%>
                <!--<input id="password-field" class= "form-control mb-2" type="text" name="Last Name" placeholder="Last Name" style="width: 565px;">-->
                <%= form.text_field :lastname, class:'form-control mb-2', placeholder:'Last Name' %>
                <!--<input id="username-field" class= "form-control mb-2" type="text" name="Email" placeholder="E-mail" style="width: 565px;">-->
                <%= form.text_field :email, type: 'email', class:'form-control mb-2', placeholder:'Email' %>
                <!--<input id="password-field" class= "form-control mb-2" type="password" name="Password" placeholder="Password" style="width: 565px;">-->
                <%= form.password_field :password, class:'form-control mb-3', placeholder:'Password' %>
                <h5>I am a <%= form.select :position, ['Manager', 'Employee'], class:'form-control'%> in my organisation</h5></br>
                <%= form.submit 'Sign Up', class:'btn btn-primary mb-3' %>
                <button class="btn btn-outline-success mb-3" type="button"  data-toggle="modal" data-target="#exampleModal">
                  Sign In
                </button>
                <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
</div>

<div class="modal" id="exampleModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="width:800px;">
      <div class="container border border-dark">
        <div class="row">
          <div class="col-md-4 login-bg text-white text-center">
            <h2><i class="fas fa-brain fa-5x mt-3"></i></h2>
            <h6 class="mb-3">"Empathy begins with understanding life from another person's perspective. </br></br> Nobody has an objective experience of reality. It's all through our own individual prisms."</h6>
          </div>
          <div class="col-md-8">
            <h1 class="text-center mt-3 login-text">Login To Your Account</h1>
            <label class="sr-only" for="inlineFormInputGroupUsername2">Email</label>
            <%= form_for :session, url: session_path do |form| %>
              <div class="input-group mb-2 mr-sm-2 mt-5">
                <div class="input-group-prepend">
                  <div class="input-group-text"><i class="fas fa-user"></i></div>
                </div>
                <%= form.text_field :email, type: 'email', class:'form-control', id:'inlineFormInputGroupUsername2', placeholder:'Email' %>
              </div>
              <label class="sr-only" for="inlineFormInputGroupUsername2">Email</label>
              <div class="input-group mb-2 mr-sm-2">
                <div class="input-group-prepend">
                  <div class="input-group-text"><i class="fas fa-lock"></i></div>
                </div>
                <%= form.password_field :password, class:'form-control', id:'inlineFormInputGroupUsername2', placeholder:'Password'%>
              </div>
                <%= form.submit class:'btn btn-primary mt-3 mb-3' %>
                <%= link_to "Sign in with Google", "/auth/google_oauth2", class:'btn btn-outline-success mt-3 mb-3' %>
            <% end %>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
$(document).on('turbolinks:load', function(){

$("#search-companies").on("keyup", function(){
  autocomplete()
});

function autocomplete(){
  $.ajax({
    url: '/companies/search',
    type: 'POST',
    data: $("#search-companies").serialize(),
    dataType: 'json',
    error: function() {
        console.log("Something went wrong");
    },
    success: function(data) {
      document.getElementById('list').innerHTML = '';
      $("#list").empty();

      var uniquedata = [];
      $.each(data, function(i, el){
          if($.inArray(el, uniquedata) === -1) uniquedata.push(el);
      });

      uniquedata.forEach(function(element) {
        var option = document.createElement("option");
        option.value = element;
        //append option to list
        $("#list").append(option);
      });
    }
  });
}
})
</script>