config/routes.rb
Rails.application.routes.draw do

  # Home / Root
  root 'welcome#index'
  get 'welcome/index'

  # Individual pages Routes
  get '/companies/:company_id/users/:id/index' => "audio#index", as:'audio_index'
  get "/companies/:id/dashboard/show" => "dashboard#show", as: "dashboard"
  get '/users/:id/video' => "video#show", as: 'user_video'
  get '/companies/:company_id/users/:id/text_analysis' => 'text#show', as: 'text_analyze'

 post 'users/:id/texts'=>'text#create', as:"text_upload"
  # Braintree Payment Routes
  get 'braintree/new'
  get 'braintree/new_six'
  get 'braintree/new_one'
  get 'braintree/pricing'
  post 'braintree/checkout'
  post 'braintree/checkout_six'
  post 'braintree/checkout_one'
  post 'braintree/checkout_one_existing'

  # Clearance Routes
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get '/show'=>"video#show"  ,as: "video_feature"

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :users, controller:'users'
  resources :companies, controller:'company'

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :companies do
    resource :request, controller: 'request'
  end

  # Google Oauth Callback Route
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  post 'braintree/checkout'
  post 'braintree/checkout_six'
  post 'braintree/checkout_one'
  get 'companies/:company_id/users/:id/confirm' => 'users#confirm', as:'confirm_user'
  get 'companies/:id/employees_index' => 'company#employees_index', as:'employees_index'
  patch 'users/:id/remove_employee' => 'company#remove_employee', as:'remove_employee'
  get '/subscribe_to_plan' => 'braintree#subscribe_to_plan', as:'subscribe_to_plan'
  get '/pricing' => 'braintree#pricing', as:'pricing'

  post '/companies/:id/search_employees' => 'company#search', as: 'search_company_employees'
  post '/companies/search' => 'company#search_all_companies', as: 'search_companies'

end

app/models/company.rb
class Company < ApplicationRecord
    mount_uploader :image, ImageUploader
    has_many :users, dependent: :destroy

    def search_employees(query)
        self.users.where("firstname ILIKE :firstname", firstname:  "%#{query}%")
    end

    def self.search_companies(query)
        where("name ILIKE :name", name: "%#{query}%")
    end
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
    def new
        @users = User.where(company_id:nil)
        @users = @users.where(position: 'employee')
        @users_options = @users.each_with_object([]) do |user, array|
            option = [user.email, user.id]
            array << option
        end
    end

    def search
        # byebug
        @company= Company.find(params[:id])
        @search_employees = @company.search_employees(params["search"])
        @user= User.find_by(firstname: params['search'])

        respond_to do |format|
            format.html { redirect_to user_path(@user.id) }
            format.json { render json: @search_employees.map{|e| e.firstname}}
        end
    end

    def search_all_companies
        @companies = Company.all
        @search_companies = Company.search_companies(params["searchcompany"])
        # byebug
        @company= Company.find_by(name: params["searchcompany"])

        respond_to do |format|
            format.html { redirect_to dashboard_path(@company.id) }
            format.json { render json: @search_companies.map{|c| c.name}}
        end
    end

    def employees_index
        @company = Company.find(params[:id])
        @employees= @company.users
    end

    def remove_employee
        @user = User.find(params[:id])
        @company_id = @user.company.id
        @user.update(company_id: nil)
        redirect_to dashboard_path(current_user.company.id)
    end

    def create
        @users = User.all
        @company = Company.new(company_params)
        @company.save
        @company.update(manager_id:current_user.id)
        current_user.update(company_id:@company.id)

        selected_ids = params[:company][:user]
        selected_ids.each do |i|
            next if i.blank?
            user = @users.find_by(id:i)
            user.update(company_id: @company.id)
        end
        redirect_to dashboard_path(@company.id)
    end

    def show
        @company = Company.find(params[:id])
        @employees = @company.users
        @manager = User.find(@company.manager_id)
    end

    def update
        @company = Company.find(params[:id])
    end

    private
    def company_params
        # Return value is a hash
        params.require(:company).permit(:name, :description, :image, :manager)
    end

    def only_manager_remove_employees
    end
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/views/company/employees_index.html.erb
<%= link_to 'Back to Company', company_path(@company.id) %> 
<h1>Employees</h1>

<ul>
<% @employees.each do |e| %>
    <% next if e.position == 'manager' %>
        <li> <%= link_to e.firstname, user_path(e.id) %> 
    <% if current_user.position == 'manager' %>|
        <%= link_to 'Remove Employee', remove_employee_path(e.id),
                    method: :patch,
                    data: { confirm: 'Remove employee?' } %></li><br/>
    <% end %>
<% end %>
<ul>

app/views/company/new.html.erb
<div class="container">
<div class="card mt-5">
  <h5 class="card-header text-center">Create a Company</h5>
  <div class="card-body">
    <%= form_with scope: :company, url: companies_path, :html => {:multipart => true}, local: true do |form| %>
      <div class="form-row">
        <div class="col">
         <label for="inputEmail4">Company Name</label>
          <%= form.text_field :name, class:'form-control border border-dark', placeholder:'Name' %>
          <small id="emailHelp" class="form-text text-muted">You cannot change this attribute once created.</small>
        </div>
        <div class="col">
         <label for="inputEmail4">Description</label>
          <%= form.text_field :description, class:'form-control border border-dark', placeholder:'Description' %>
          <small id="emailHelp" class="form-text text-muted">Write a short description of your company. (Max 100 characters)</small>
        </div>
      </div>
      <p class="mt-3">
      <%= form.label :"Add Employees" %><br>
      <%= form.select :user, options_for_select(@users_options), {:include_blank => false, :multiple => true}, {class:'form-control border border-dark'} %>
      </p>

      <p>
        <%= form.submit 'Create Your Company', class:'btn btn-success', style:'width:100%' %>
      </p>
    <% end %>
  </div>
</div>

</div>

app/views/company/search.js.erb
<!-- $("#list").html();
<% @search_employees.each do |employee| %>
var option = document.createElement("option");
option.value = "<%= employee.firstname %> | <%= employee.company.name.upcase %>";

//append option to list
$("#list").append(option);
<% end %>; 

app/views/company/show.html.erb
<img src=<%= @company.image_url(:thumb).to_s %>>

<h1><%=@company.name.upcase%></h1>

<h3>Manager: <%=@manager.firstname%>  <%=@manager.lastname%></h3>

<%= form_with url: search_company_employees_path(@company.id), local: true, class:'form-inline my-2 my-lg-0' , :method => 'post', id: "employee-search"  do |form| %>
    <%= form.text_field :search, class: "form-control mr-sm-2", list: 'list' %>
    <%= form.submit "search", class:"btn btn-outline-success my-2 my-sm-0" %>
    <datalist id="list"></datalist>
<% end %>

<%= link_to 'Employees', employees_index_path(@company.id) %></h3>

<% if current_user.position != 'manager' && current_user.company_id == nil %>
  <%= form_with scope: :company, url: company_request_path(@company.id), local: true do |form| %>
    <p>
      <%= form.submit "Request Join", class: "btn btn-primary btn-xs" %>
    </p>
  <% end %>
<% end %>

<script>
$(document).on('turbolinks:load', function(){

$("#search").on("keyup", function(){
  autocomplete()
});

function autocomplete(){
  $.ajax({
    url: '/companies/<%= @company.id %>/search_employees',
    type: 'POST',
    data: $("#employee-search").serialize(), 
    dataType: 'json', 
    error: function() {
        console.log("Something went wrong");
    },
    success: function(data) {
      document.getElementById('list').innerHTML = '';
      console.log('helo')
      $("#list").empty();

      var uniquedata = [];
      $.each(data, function(i, el){
          if($.inArray(el, uniquedata) === -1) uniquedata.push(el);
      });

      uniquedata.forEach(function(element) {
        var option = document.createElement("option");
        option.value = element;
        //append option to list
        $("#list").append(option);
      });
    }
  });
}
})
</script>